[package]
name = "pipeviewer"
version = "0.1.0"
authors = ["Arman <armanshah360@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
crossbeam = "0.7.3"